### ISSUE TITLE
Beta 03 changes

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#10]
In his feedback to the changes in the Beta campaign, AlexTheDacian said that the first Collective attack group in Beta 03
 is vulnerable to Cyborg attacks. Could you please add three HMG Tiger Tracked units at the red crosses?

![Beta 03](https://user-images.githubusercontent.com/47194838/95451896-bf8efd00-0968-11eb-9e48-31f25f077505.jpg)

**Comment by KJeff01** [comment]
Done. Unfortunately, I don't know how to add _custom_ droids to Flame and every time I've tried they never show up for whatever reason. So, until then, they are added via the script itself.

**Comment by AlexTheDacian** [comment]
@KJeff01 if I knew this was up I would've guided you in. To add custom droids in FlaME from what I do remember, you need to first drop whatever unit you want from the default Droid list, then go to the **Object** tab, and there you can see this button called **Convert Templates to Design**. First select the unit you want to change, then click the button and confirm. You'll be able then to change the components at your own desire. With a little bit of experimentation, you can get it to work.
