### ISSUE TITLE
New Nexus defenses in Gamma 04

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#17]
I want to move some upgrades to Gamma 04 but there are no structures where we can put an artifact in.
In the two pictures, I built HVC Hardpoints where the Nexus Hardpoints could be.
![wz2100-20201216_144657-SUB_3_2](https://user-images.githubusercontent.com/47194838/102359327-f0b32b80-3fb0-11eb-8432-73fb19aa5127.png)
![wz2100-20201216_144903-SUB_3_2](https://user-images.githubusercontent.com/47194838/102359370-fa3c9380-3fb0-11eb-93fe-0c1613a2ad80.png)
In the first picture, they stand at the tiles 17/33 and 24/34, in the second one at the tiles 19/34 and 20/34. I prefer the second one because they can concentrate their fire. Makes it more difficult to destroy them.
Right now I'm working on how to split the artifacts in Gamma. I'll get in touch with my suggestions in the next few days.

**Comment by KJeff01** [comment]
We could also drop the artifacts from the Nexus units already on the map directly south of Alpha team, if that would work for your ideas.

**Comment by highlander1599** [comment]
Would also work. I just need an artifact at this level.

**Comment by highlander1599** [comment]
Works with the artifact dropped from the Cyborg. Close this issue.
