### ISSUE TITLE
Gamma campaign research changes

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#18]
Here are my suggestions for the Gamma campaign research. Only changes in comparison to the master version are mentioned:

Gamma 01: 
- Depleted Uranium MG Bullets MK 2 goes to Gamma 02
- HVAPFSDS Cannon Rounds MK 2 goes to Gamma 02
- HVAPFSDS Cannon Rounds MK 3 goes to Gamma 04
- HEAP Howitzer Shells MK 2 goes to Gamma 02
- HEAP Howitzer Shells MK 3 goes to Gamma 04
- AA HEAP Flak MK 2 goes to Gamma 02
- AA HEAP Flak MK 3 goes to Gamma 04

Gamma 02:
New artifact Depleted Uranium MG Bullets MK 2 in the Factory
 - Depleted Uranium MG Bullets MK 2 leads to HVAPFSDS Cannon Rounds MK 2
 - HVAPFSDS Cannon Rounds MK 2 leads to HEAP Howitzer Shells MK 2 and AA HEAP Flak MK 2

Gamma 03:
Cannon Rapid Loader MK 2-3 are going to Gamma 04

Gamma 04:
New artifact Cannon Rapid Loader MK 2 (either from a Cyborg or from new implemented Hardpoints)
 - Cannon Rapid Loader MK 2 leads to Cannon Rapid Loader MK 3 and AA Chainfeed Loader MK 2
 - AA Chainfeed Loader MK 2 leads to AA Chainfeed Loader MK 3
 - Cannon Rapid Loader MK 3 leads to HVAPFSDS Cannon Rounds MK 3
 - HVAPFSDS Cannon Rounds MK 3 leads to HEAP Howitzer Shells MK 3 and AA HEAP Flak MK 3

Gamma 06:
Vindicator SAM and Vindicator SAM Site are going to Gamma 07

Gamma 07: 
 - Hardened Rail Dart MK 3 goes to Gamma 09
 - Rail Gun ROF MK 3 goes to Gamma 09
 - Search & Destroy Missiles leads to Vindicator SAM
 - Vindicator SAM leads to Vindicator SAM Site

Gamma 09:
 - Gauss Cannon leads to Hardened Rail Dart MK 3
 - Hardened Rail Dart MK 3 leads to Rail Gun ROF MK 3

**Comment by KJeff01** [comment]
Preliminary results with 743e8b1d9f7a8cdfff7326f503a02ef4cdc8ceea. Have not tested it yet.

**Comment by highlander1599** [comment]
The first test failed. In Gamma 01 the reinforcement timer is set to 7 instead of 5 minutes and the first research topics you have without getting an artifact (Rotary Howitzer – Hellstorm and Depleted Uranium MG Bullets) are not researchable after I built a research facility.
[WZlog-1221_104155.txt](https://github.com/KJeff01/camBalance/files/5723584/WZlog-1221_104155.txt)
[rules.0.log](https://github.com/KJeff01/camBalance/files/5723586/rules.0.log)
[cam3-a.0.log](https://github.com/KJeff01/camBalance/files/5723587/cam3-a.0.log)

**Comment by KJeff01** [comment]
Should be fixed now. I ran through the entire Gamma campaign quickly and didn't encounter any assert messages.

**Comment by highlander1599** [comment]
I'm at my mother atm and can't test it before tuesday.

**Comment by highlander1599** [comment]
Can confirm. Works as it should.
