### ISSUE TITLE
Alpha 03 too strong

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#2]
VanitiesFiend fears that new players could fail too often in Alpha 03 because of the new Scav structures you implemented. Is it possible to switch the Scav bunkers only in Alpha 03 to HARD structures for easy difficulty? If not, just say no and close this issue.

**Comment by KJeff01** [comment]
This is a strange suggestion... Flamer + Bunker = bad time for bunker. Not only that but it would mean the bunker would heavily resist flamers just on that mission.

I don't remember how hard that mission on camBalance is but it couldn't be that hard to just grab the artifact. I do know it's challenging to 100% destroy everything in the short timer, though.

**Comment by highlander1599** [comment]
DZiq failed several times to win Alpha 03.  So I changed the title again. I didn't want to open a new issue. I asked VanitiesFiend and Dziq what they want to have changed. I tell you their suggestions as soon as they answered me.

**Comment by highlander1599** [comment]
I figured out what the problem for Dziq is. The red arrow marked units are moving to the green circle as soon as you attack the two MG bunkers. And 8 Scav units at the same time, maybe together with one or two produced units are a little bit too much at the same time. Can we change their behavior that way, that the south group is attacking when the bunkers are destroyed and the north group is attacking when the player enters the Scav base?
![OWgKJHm](https://user-images.githubusercontent.com/47194838/89302473-293e1280-d66b-11ea-86a1-5ceddd2b94ca.jpg)

**Comment by KJeff01** [comment]
@highlander1599 What do you think of 912b72a8ddbdb548ebddc785e2e7fee52d825fa9?

**Comment by highlander1599** [comment]
A few more suggestions. For a new player, the two western Scav groups can become a problem because after you captured the artifact these two groups get united when they start hunting the player. And with the stronger weapons, they can become too difficult to destroy. So I suggest starting the southern of the two western groups when the factory gets attacked and the northern one when the artifact is captured. We should also add a trigger area for the activation of the Scav factory. At the moment production starts when the transporter has landed. I suggest a trigger area with the coordinates pos1: 1856, 4672; pos2: 2496, 4928.

**Comment by KJeff01** [comment]
Done.

I'll note doing something specific for that one group when picking up the artifact would be useless since the player will have completed the objectives and all units will want to find and attack the player.

**Comment by highlander1599** [comment]
It's ok know. Closing this issue.
