### ISSUE TITLE
Alpha 03 too hard

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#22]
I got feedback via Discord that Alpha 03 with all the Flamer Towers is too hard for beginners. As a first step please remove Flamer Tower 3 in the picture below. I also made a few changes to the BabaFlame weapon. If the feedbacks are positive I'll open a PR with these changes.
![Alpha 03 Flamer](https://user-images.githubusercontent.com/47194838/104526389-8d91d480-5602-11eb-9975-d1f6bf789152.jpg)

**Comment by KJeff01** [comment]
Tower 3 removed.

**Comment by highlander1599** [comment]
Thank you. I will give the members on Discord a mod and wait for feedback.
