### ISSUE TITLE
Problems with debug mode

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#24]
I started a new Alpha campaign with version 3.4.1 for a few tests and went into debug mode. After I activated the biffer baker cheat I couldn't collect the artifacts and a huge log file was created
[logs.zip](https://github.com/KJeff01/camBalance/files/5832487/logs.zip)

**Comment by KJeff01** [comment]
The mod is only compatible with the development builds since 4d6a9100ebb2eab916008b407b498dacdbbbbe65.

**Comment by highlander1599** [comment]
Ah, ok. That explains some problems with older saved games.
