### ISSUE TITLE
Beta Campaign Research Changes Request

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#3]
Here are my suggested changes for Beta Campaign research changes for the project until Beta 5.

### Beta 01

HEAP Mini Rockets only proceed to MK 1 (MK 2 moves to Beta 03, MK 3 to Beta 06)
HEAP Mini Rockets activates HESH Rocket Warhead MK 1 (MK 2 moves to Beta 03, MK 3 to Beta 08)
Rapid Fire Chaingun Upgrade activates Tungsten-Tipped MG Bullets MK 1 (MK 2 moves to Beta 03, MK 3 to Beta 06)
APFSDS Cannon Rounds proceed only to MK 1 (MK 2 moves to Beta 03)
__________

### Beta 03

Rocket Autoloader activates HEAP Mini-Rockets MK 2 and HESH Rocket Warhead MK 2
Replace Medium Body - Panther (moves to Beta 05) with Light Body - Leopard. Activates the same upgrades as the Medium Body before.
Hyper Fire Chaingun Upgrade activates Tungsten Tipped MG Bullets MK 2
New Artifact in the Cyborg Factory of the Middle Base: Cannon Autoloader
Cannon Autoloader activates the APFSDS Cannon Rounds MK 2
__________

### Beta 05

Ripple Rockets don't activate HESH Rocket Warhead MK 3 (moves to Beta 09)
Howitzer activates Howitzer Autoloader MK 1 (MK 2 moves to Beta 07, MK 3 to Beta 10)
Howitzer activates HE Howitzer Shells MK 1 (MK 2 moves to Beta 07)
Replace Light Body - Leopard with Medium Body - Panther. Activates the same upgrades as the light body before
Robotic Factory Production doesn't activate Cannon Autoloader MK 2 (moves to Beta 06) and Mortar Autoloader MK 3 (moves to Beta 08) but only Mortar Autoloader MK 2.

Edit: Decreasing the Cannon damage upgrades 4-6 to 20 from 30.

**Comment by KJeff01** [comment]
@highlander1599 Your suggestion have been implemented now (you should double-check). Anything that would go past Beta 5 has simply been disabled at the moment but the effect is still the same.

**Comment by highlander1599** [comment]
Thank you. I'll check it in the next days. I think until next weekend I can give you the research changes for the rest of the Beta missions.

**Comment by highlander1599** [comment]
@KJeff01 I see that you haven't noticed my edit in the original comment. Now that you have implemented the other suggestions I can decrease the damage upgrades values on my own. I send you a PR for that.

**Comment by highlander1599** [comment]
I encountered the following issues:
Beta 03: Rocket Autoloader activates HEAP Mini-Rockets MK 2+3 but should only activate MK 2. Hyper Fire Chaingun Upgrade activates Tungsten Tipped MG Bullets MK 2+3 but should only activate MK 2.
Beta 05: Turbo Charged Engine now missing in the VTOL research path

Anything else works as it should.

**Comment by highlander1599** [comment]
Is it easier for you if I give you my suggestions for the rest of the Beta campaign in one issue or should I split them?

**Comment by KJeff01** [comment]
> I encountered the following issues:
> Beta 03: Rocket Autoloader activates HEAP Mini-Rockets MK 2+3 but should only activate MK 2. Hyper Fire Chaingun Upgrade activates Tungsten Tipped MG Bullets MK 2+3 but should only activate MK 2.
> Beta 05: Turbo Charged Engine now missing in the VTOL research path

Fixed.

You can add all your Beta suggestions to this issue.

**Comment by highlander1599** [comment]
And now moving forward

### Beta 06

Rocket Autoloader MK 2 activates HEAP Mini-Rockets MK 3
Hyper Velocity Cannon moves to Beta 08
New artifact in the factory where the HVC was: Cannon Autoloader MK 2
The Assault Gun activates Tungsten-Tipped MG Bullets MK 3

-----

### Beta 07

Target Acquisiton Artilley Shells proceed only to MK 1 (MK 2 moves to Beta 10)
New artifact in a Howitzer emplacement of your choice: HE Howitzer Shells MK 2
HE Howitzer Shells MK 2 activates Howitzer Autoloader MK 2

-----

### Beta 08

Rotary Mortar - Pepperpot activates Mortar Autoloader MK 3
New artifact in the Factory in the Northeast: Hyper Velocity Cannon
Hyper Velocity Cannon activates HVC Emplacement and HVC Hardpoint

-----

### Beta 09

AFPSDS Cannon Rounds activates Cannon Autoloader MK 3
Rocket Autoloader MK 3 gets replaced by HESH Rocket Warhead MK 3
HESH Rocket Warhead MK 3 activates Rocket Autoloader MK 3 (looks odd, is because of consistency with the Cannon Autoloader)

-----

### Beta 10

HE Howitzer Shells MK 3 activates Howitzer Autoloader MK 3 and Target Acquisition Shells MK 2

**Comment by KJeff01** [comment]
Attempted your suggestions in 9e04d8ad4253ec13f21a8b51817fc3de55ff7527 though I need to test it still.

**Comment by KJeff01** [comment]
I have added the entire Beta tech tree into transitionTech.js. It appears that all the right tech is indeed being granted compared to the base game albeit in a different order of course.

There are some upgrades that don't get researched until a transition to a new campaign. Below are the ones we can potentially add artifacts, or unlock, somewhere.

Alpha:
"R-Vehicle-Engine03"
"R-Defense-HvyMor"


Beta:
"R-Wpn-Mortar-Damage04"
"R-Wpn-Mortar-Damage05"
"R-Wpn-Mortar-Damage06"
"R-Wpn-Bomb-Accuracy02"

**Comment by highlander1599** [comment]
I will have a look at it on Monday.

**Comment by highlander1599** [comment]
Research changes for the Beta campaign are working fine. I had a look at the weapons at the end of the Beta campaign and found Lancer and Tank Killer way overpowered. I will do some calculations and tests and send you a PR with the weapon changes.
Here my suggestions for the unresearched upgrades:
Alpha 08 Heavy Mortar - Bombard activates R-Defense-HvyMor
Alpha 12 Hover Propulsion activates R-Vehicle-Engine03
Beta 07 Heap Bomb Bay activates R-Wpn-Bomb-Accuracy02
Beta 03 One of the 4 Mortar pits in the NW Base gets the new artifact R-Wpn-Mortar-Damage04
Beta 05 Mortar Autoloader MK 2 activates R-Wpn-Mortar-Damage05
Beta 08 Mortar Autoloader MK 3 activates R-Wpn-Mortar-Damage06
I would also suggest to replace all Mortar Pits in the Beta campaign by Bombard Pits now that they are researched.

**Comment by highlander1599** [comment]
With my rebalancing, I also changed some values in research.json. I will wait until you implemented the research changes and make my PR basing on that.

**Comment by KJeff01** [comment]
@highlander1599 Research suggestions implemented.
