### ISSUE TITLE
Ingame message that a research upgrade isn't found

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#31]
I started a new campaign with master 1ad6625 and got the ingame message that there is no MG-ROF01 upgrade. In the logs are several messages that a lot of researches weren't found.
[logs.zip](https://github.com/KJeff01/camBalance/files/5952542/logs.zip)
Edit: I now tried to play on but after I build the CC I couldn't design any units.
More Edit: No problems without the mod

**Comment by highlander1599** [comment]
pastdue changed the wzapi.cpp in commit f63dc04. Maybe this causes the problems

**Comment by highlander1599** [comment]
Ok, it looks I messed up when I tried to implement your changes in PR 30. Will try it again.

**Comment by highlander1599** [comment]
Idk what I did wrong. Can you have a look at it, please?


[research.zip](https://github.com/KJeff01/camBalance/files/5952880/research.zip)

**Comment by highlander1599** [comment]
Looks like I found the mistake. Read my comment in PR 30. With this change, I encounter no error messages anymore.

**Comment by highlander1599** [comment]
Fuck. I forgot to use the mod. Also with my change I mentioned, the error message occurs.

**Comment by KJeff01** [comment]
"R-Wpn-Missile-Damage02" has a missing comma in the required research array.

BTW this site might save you a few headaches: [JSONLint](https://jsonlint.com/).

**Comment by highlander1599** [comment]
Yep, it was this damn fucking missing comma. Works now.
