### ISSUE TITLE
Phantom Factories in Gamma 04 are producing too soon

### ISSUE THREAD

**Issue by highlander1599** [KJeff01/camBalance#39]
I entered Gamma 04 with camBalance and the Phantom Factories in the SW and the NE produced immediately after my arrival reinforcements and sent them to the LZ. This results in 14 Cyborgs at the LZ less than a minute after I landed. Even a Hero Commander with Hero Flashlights has no chance against such numerous superior army.

**Comment by KJeff01** [comment]
They are too tough in camBalance? We did this so a player couldn't rush in and rescue Alpha team and beat the mission in like 3 minutes.

I think an alternative is to make them patrol a ton of positions on the map.

**Comment by KJeff01** [comment]
Could you give me your save before going into the offworld part?

**Comment by highlander1599** [comment]
I think with all the research changes they became simply too tough. I think it would be ok if the units from the NE factory are immediately on the map and the SW factory follows 2 minutes later.

I made a stupid mistake at the beginning of my walkthrough, so you have to name the mod camBalance-master-orig
[Gamma 04.zip](https://github.com/KJeff01/camBalance/files/6110768/Gamma.04.zip)

BTW, is there the opportunity to change the name of the required mod?

**Comment by KJeff01** [comment]
You could try changing the names of the mod in gameInfo.json and main.json

What are your thoughts on removing:
```
phantomFactoryNE();
phantomFactorySW();
```

and changing the patrol queue into:
`queue("setupPatrolGroups", camMinutesToMilliseconds(1.5));`

in cam3-2's eventStartLevel?

**Comment by highlander1599** [comment]
I'm not sure what would be the result because of my not existing programming knowledge. Do I understand it right, that the units from the phantom factories would be removed and the patrols are starting later?

**Comment by KJeff01** [comment]
Yep. The initial spawns that happen right away would not happen and the units on the map will stay still for longer.

These guys are more like Terminators so giving the player a chance to breathe might be good enough.

**Comment by highlander1599** [comment]
We should give it a try and see how it works. If it's then too easy we can still make it step by step harder.

**Comment by highlander1599** [comment]
> You could try changing the names of the mod in gameInfo.json and main.json in your save.

Didn't work. :( 
[WZlog-0309_204121.txt](https://github.com/KJeff01/camBalance/files/6111004/WZlog-0309_204121.txt)

**Comment by KJeff01** [comment]
I'll try to beat it on Insane.

**Comment by KJeff01** [comment]
I have pushed a baseline commit that I tested to beat Gamma 4 on Insane.

Used Python Tracked Inferno, Mantis Assault-Gun Half-Tracks, a Tiger Hover Commander, and brought in your available Assault-Cannon units on the map. Built Sensor towers and Hellstorms and a few whirlwinds to keep the LZ safe.

**Comment by highlander1599** [comment]
Maybe I can do some tests on Friday. In my few attempts today I had the feeling that the Pulse Laser needs a buff. Stay tuned. ;)

**Comment by highlander1599** [comment]
I made a first test and the level is now beatable with Insane difficulty. Maybe we can bring back the NE group but I can't check this until Monday.

**Comment by highlander1599** [comment]
Fixed with #44
