### ISSUE TITLE
Chokepoint Alpha 12

### ISSUE THREAD

**Issue by Brutaz** [KJeff01/camBalance#43]
Hello,

We discussed the chokepoint problem for Alpha12 on Discord. As you can see on the screenshot, and have probably experienced yourself as well,  a lot of units tend to get stuck at that point.
So here is my proposition: (I'm lazy so I just copied this from Discord)
What if, we shifted the whole left part 1 tile to the left. Put left MachineGunBunker right in front of the wall(in front of the lancer HP) without any gap. 
For right side: Move Lancer HP 1 tile right, shift Flamertower 1 tile right, move right Lancer onto toe right cross wall. Put right MachineGunBunker in front of lancer HP(no gap in between either)
thus creating a 3gap opening
And the MGB's would no longer be in path of the tanks.
I don't think making the gap only 2 tiles wide would be sufficient. A lot of tanks tend to get stuck there, I had playthroughs where there were 100+ units stuck.

Greets 
Sam

![Warzone 2100 13-Mar-21 20_06_00](https://user-images.githubusercontent.com/69391176/111042305-0f548180-843d-11eb-9bff-4beb075d85d8.png)

**Comment by KJeff01** [comment]
Fixed in latest WZ dev build.
